name: depth_blur_algo
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <oussamamaatallah01@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  image: ^2.1.9

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
